# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models


def get_default_branch_name():
    from django.conf import settings
    try:
        return settings.DEF_BRANCH
    except AttributeError:
        return "master"


class Migration(migrations.Migration):

    dependencies = [
        ('codespeed', '0002_median'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_branch',
            field=models.CharField(default=get_default_branch_name, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
